## author:      jesus.llorente@gmail.com
## date:        10/09/2020
## description: Development VM for Realm Gateway & Customer Edge Switching
## notes:       Run `vagrant rsync-auto` on a separate terminal to keep _synced_ folders up to date

Vagrant.configure(2) do |config|
    # Define default values
    config.ssh.insert_key = false

    ## Realm Gateway
    config.vm.define "rgw-dev" do |node|
        #node.vm.box = "ubuntu/bionic64"
        node.vm.box = "ubuntu/focal64"
        node.vm.hostname = "rgw-dev"
        # requires: vagrant plugin install vagrant-disksize
        node.disksize.size = '25GB'

        # Configure VM specs per provider
        ## VirtualBox
        node.vm.provider "virtualbox" do |provider|
            provider.name = "rgw-dev"
            provider.customize ["modifyvm", :id, "--memory", 3072, "--cpus", 6, "--paravirtprovider", "default"]
            provider.customize ["modifyvm", :id, "--nictype1", "virtio"]
            # Further tweaks to improve performance (jiffies)
            provider.customize ["modifyvm", :id, "--chipset", "ich9"]
            provider.customize ["modifyvm", :id, "--pae", "on", "--hwvirtex", "on"]
            provider.customize ["modifyvm", :id, "--nestedpaging", "on", "--nested-hw-virt", "on"]
            provider.customize ["modifyvm", :id, "--vtxvpid", "on", "--vtxux", "on"]
        end

        ### Libvirt
        #node.vm.provider "libvirt" do |provider|
        #    provider.cpus = 6
        #    provider.memory = "3072"
        #    provider.cpu_model = "host-passthrough"
        #    #provider.nic_model_type = "e1000"
        #    provider.storage :file, :size => '25G', :type => 'raw'
        #end

        # Create port forwarding for SSH
        node.vm.network "forwarded_port", guest: 22,  host: 5555, host_ip: "127.0.0.1", id: "ssh"

        # Configure shared folders
        node.vm.synced_folder ".", "/vagrant", disabled: true
        # The rsync mount preserves the file permissions needed when deploying LXC containers
        node.vm.synced_folder "../../", "/home/vagrant/RealmGateway", type: "rsync", rsync__args: ["--verbose", "--archive", "-z", "--copy-links"]

        # Run installation scripts
        node.vm.provision "shell", inline: <<-SHELL
            # Create this symlink because some init scripts are hard-coded to use /RealmGateway
            ln -snf /home/vagrant/RealmGateway /RealmGateway
            # Execute provisioning script to install dependencies for LXC and network namespace deployments
            #cd /RealmGateway/provisioning/virtual_machine/
            #./provision_lxc_deployment.sh
            #./provision_netns_deployment.sh
        SHELL

        # Display post-up message
        #node.vm.post_up_message = "VM is ready, use `vagrant ssh rgw-dev` to connect to it."
    end
end
