## author:      jesus.llorente@gmail.com
## date:        10/09/2020
## description: Development VM for Realm Gateway & Customer Edge Switching

# Network bridges:
# br-mgt0 br-wan0 br-wan1 br-wan2 br-wan1-gwa br-wan2-gwb br-lan0-gwa br-lan0-gwb br-lan0-ngwa br-lan0-ngwb

Vagrant.configure(2) do |config|
    # Define default values
    config.ssh.insert_key = false
    #config.vm.box = "fgrehm/precise64-lxc"
    #config.vm.box = "debian/stretch64"
    config.vm.box = "emptybox/ubuntu-bionic-amd64-lxc"
end

load File.expand_path("router/Vagrantfile") if File.exists?("router/Vagrantfile")
load File.expand_path("public/Vagrantfile") if File.exists?("public/Vagrantfile")
load File.expand_path("proxygwa/Vagrantfile") if File.exists?("proxygwa/Vagrantfile")
load File.expand_path("gwa/Vagrantfile") if File.exists?("gwa/Vagrantfile")
load File.expand_path("testgwa/Vagrantfile") if File.exists?("testgwa/Vagrantfile")
load File.expand_path("nestgwa/Vagrantfile") if File.exists?("nestgwa/Vagrantfile")
load File.expand_path("testnestgwa/Vagrantfile") if File.exists?("testnestgwa/Vagrantfile")
