## author:      jesus.llorente@gmail.com
## date:        10/09/2020
## description: Development VM for Realm Gateway & Customer Edge Switching

Vagrant.configure(2) do |config|
    ## public.demo
    config.vm.define "public" do |node|
        node.vm.hostname = "public"

        # Configure shared folders
        node.vm.synced_folder ".", "/vagrant", disabled: true
        # Use one-off file provisioner maintaining file permission
        node.vm.provision "file", source: "./common/rootfs", destination: "/var/tmp/rootfs"
        node.vm.provision "file", source: "./public/rootfs", destination: "/var/tmp/rootfs"

        # Install apt package dependencies
        node.vm.provision "shell", inline: <<-SHELL
            export DEBIAN_FRONTEND=noninteractive
            unlink /etc/resolv.conf || true
            echo 'nameserver 8.8.8.8' > /etc/resolv.conf
            apt install -y apt-transport-https && apt update
            apt install -y arping curl dnsutils ethtool tcpdump lksctp-tools
            apt install -y ftp vsftpd iperf
        SHELL

        # Configure common services
        node.vm.provision "shell", inline: <<-SHELL
            systemctl stop apt-daily.timer apt-daily-upgrade.timer systemd-resolved
            cp -R /var/tmp/rootfs/* /
            systemctl daemon-reload
            systemctl enable runatstartup
            systemctl start runatstartup
        SHELL

        # Configure specific services
        node.vm.provision "shell", inline: <<-SHELL
            echo 'nameserver 100.64.0.1' > /etc/resolv.conf
            ip route change default via 100.64.0.1
            systemctl restart vsftpd
        SHELL

        # Configure container networking
        node.vm.provider :lxc do |lxc|
            lxc.container_name = :machine

            # Clear network configuration
            lxc.customize "net", ""

            # Management interface
            lxc.customize "net.0.type",         "veth"
            lxc.customize "net.0.flags",        "up"
            lxc.customize "net.0.link",         "br-mgt0"
            lxc.customize "net.0.name",         "mgt0"
            lxc.customize "net.0.veth.pair",    "public-mgt0"
            lxc.customize "net.0.ipv4.address", "10.0.0.13/24"
            lxc.customize "net.0.ipv4.gateway", "10.0.0.1"

            # WAN interface
            lxc.customize "net.1.type",         "veth"
            lxc.customize "net.1.flags",        "up"
            lxc.customize "net.1.link",         "br-wan0"
            lxc.customize "net.1.name",         "wan0"
            lxc.customize "net.1.veth.pair",    "public-wan0"
            lxc.customize "net.1.ipv4.address", "100.64.0.100/24"
            lxc.customize "net.1.ipv4.address", "100.64.0.101/24"
            lxc.customize "net.1.ipv4.address", "100.64.0.102/24"
            lxc.customize "net.1.ipv4.address", "100.64.0.103/24"
            lxc.customize "net.1.ipv4.address", "100.64.0.104/24"
            lxc.customize "net.1.ipv4.address", "100.64.0.105/24"
            lxc.customize "net.1.ipv4.address", "100.64.0.106/24"
            lxc.customize "net.1.ipv4.address", "100.64.0.107/24"
            lxc.customize "net.1.ipv4.address", "100.64.0.108/24"
            lxc.customize "net.1.ipv4.address", "100.64.0.109/24"
            lxc.customize "net.1.ipv4.address", "100.64.0.110/24"
            #lxc.customize "net.1.ipv4.gateway", "100.64.0.1"
        end
    end
end
