## author:      jesus.llorente@gmail.com
## date:        10/09/2020
## description: Development VM for Realm Gateway & Customer Edge Switching

Vagrant.configure(2) do |config|
    ## nestgwb.demo
    config.vm.define "nestgwb" do |node|
        node.vm.hostname = "nestgwb"

        # Configure shared folders
        node.vm.synced_folder ".", "/vagrant", disabled: true
        # Use one-off file provisioner maintaining file permission
        node.vm.provision "file", source: "./common/rootfs", destination: "/var/tmp/rootfs"
        node.vm.provision "file", source: "./nestgwb/rootfs", destination: "/var/tmp/rootfs"
        # This shared mount does not preserve permissions but it remains _up-to-date_ for running code
        node.vm.synced_folder "/RealmGateway", "/RealmGateway"

        # Install apt package dependencies
        node.vm.provision "shell", inline: <<-SHELL
            export DEBIAN_FRONTEND=noninteractive
            unlink /etc/resolv.conf || true
            echo 'nameserver 8.8.8.8' > /etc/resolv.conf
            apt install -y apt-transport-https && apt update
            apt install -y build-essential git python3-dev python3-pip ipython3 libnetfilter-queue-dev libnfnetlink-dev
            apt install -y iptables ipset conntrack python3-yaml openvswitch-switch openvswitch-vtep
            apt install -y dnsutils curl htop ethtool isc-dhcp-server dnsmasq nginx tmux tree psmisc tmux tcpdump iperf
        SHELL

        # Install Python dependencies
        node.vm.provision "shell", inline: <<-SHELL
            python3 -m pip install --upgrade pip setuptools
            python3 -m pip install --upgrade --use-feature=2020-resolver aiohttp dnspython==1.16.0 python-iptables pyroute2 ryu scapy
            python3 -m pip install --upgrade -U git+https://github.com/kti/python-netfilterqueue
        SHELL

        # Configure common services
        node.vm.provision "shell", inline: <<-SHELL
            systemctl stop apt-daily.timer apt-daily-upgrade.timer systemd-resolved
            cp -R /var/tmp/rootfs/* /
            chmod 600 /root/.ssh/id_rsa
            systemctl daemon-reload
            systemctl enable runatstartup && systemctl start runatstartup
        SHELL

        # Configure specific services
        node.vm.provision "shell", inline: <<-SHELL
            # User gwa as resolver and default gateway
            echo 'nameserver 192.168.0.1' > /etc/resolv.conf
            ip route change default via 192.168.0.1
            # Restart sidecar service(s)
            systemctl restart dnsmasq
            systemctl restart isc-dhcp-server
            systemctl restart nginx
            # Start realmgateway service(s)
            systemctl start sdn-controller
            systemctl start realmgateway
        SHELL

        # Configure container networking
        node.vm.provider :lxc do |lxc|
            lxc.container_name = :machine

            # Clear network configuration
            lxc.customize "net", ""

            # Management interface
            lxc.customize "net.0.type",         "veth"
            lxc.customize "net.0.flags",        "up"
            lxc.customize "net.0.link",         "br-mgt0"
            lxc.customize "net.0.name",         "mgt0"
            lxc.customize "net.0.veth.pair",    "nestgwb-mgt0"
            lxc.customize "net.0.ipv4.address", "10.0.0.22/24"
            lxc.customize "net.0.ipv4.gateway", "10.0.0.1"

            # WAN interface
            lxc.customize "net.1.type",         "veth"
            lxc.customize "net.1.flags",        "up"
            lxc.customize "net.1.link",         "br-lan0-gwb"
            lxc.customize "net.1.name",         "wan0"
            lxc.customize "net.1.veth.pair",    "nestgwb-wan0"
            lxc.customize "net.1.ipv4.address", "192.168.0.10/24"
            lxc.customize "net.1.ipv4.address", "192.168.0.11/24"
            lxc.customize "net.1.ipv4.address", "192.168.0.12/24"
            lxc.customize "net.1.ipv4.address", "192.168.0.13/24"
            lxc.customize "net.1.ipv4.address", "192.168.0.14/24"
            #lxc.customize "net.1.ipv4.gateway", "192.168.0.1"

            # LAN interface
            lxc.customize "net.2.type",         "veth"
            lxc.customize "net.2.flags",        "up"
            lxc.customize "net.2.link",         "br-lan0-ngwb"
            lxc.customize "net.2.name",         "lan0"
            lxc.customize "net.2.veth.pair",    "nestgwb-lan0"
            lxc.customize "net.2.ipv4.address", "192.168.10.1/24"
        end
    end
end
