## author:      jesus.llorente@gmail.com
## date:        10/09/2020
## description: Development VM for Realm Gateway & Customer Edge Switching

Vagrant.configure(2) do |config|
    ## proxygwb.demo
    config.vm.define "proxygwb" do |node|
        node.vm.hostname = "proxygwb"

        # Configure shared folders
        node.vm.synced_folder ".", "/vagrant", disabled: true
        # Use one-off file provisioner maintaining file permission
        node.vm.provision "file", source: "./common/rootfs", destination: "/var/tmp/rootfs"
        node.vm.provision "file", source: "./proxygwb/rootfs", destination: "/var/tmp/rootfs"

        # Install apt package dependencies
        node.vm.provision "shell", inline: <<-SHELL
            export DEBIAN_FRONTEND=noninteractive
            unlink /etc/resolv.conf || true
            echo 'nameserver 8.8.8.8' > /etc/resolv.conf
            apt install -y apt-transport-https && apt update
            apt install -y arping dnsutils ethtool tcpdump
            apt install -y iptables ipset git openvswitch-switch openvswitch-vtep python3-pip
        SHELL

        # Install Python dependencies
        node.vm.provision "shell", inline: <<-SHELL
            python3 -m pip install --upgrade pip setuptools
            python3 -m pip install --upgrade --use-feature=2020-resolver python-iptables
        SHELL

        # Configure common services
        node.vm.provision "shell", inline: <<-SHELL
            systemctl stop apt-daily.timer apt-daily-upgrade.timer systemd-resolved
            cp -R /var/tmp/rootfs/* /
            systemctl daemon-reload
            systemctl start runatstartup
        SHELL

        # Configure specific services
        node.vm.provision "shell", inline: <<-SHELL
            # HACK: Get library from Github
            git clone https://github.com/jllorente/helpers_n_wrappers /usr/lib/python3/dist-packages/helpers_n_wrappers || true
            # Remove default gateway due to custom routing
            ip route delete default
            # Default operation mode - pseudowire without proxy
            systemctl start  synproxy-disable
        SHELL

        # Configure container networking
        node.vm.provider :lxc do |lxc|
            lxc.container_name = :machine

            # Added for testing Netmap / Modify as "ls -lah /dev/netmap"
            lxc.customize "cgroup.devices.allow", "c 10:54 rwm"
            lxc.customize "apparmor.profile",     "unconfined"

            # Clear network configuration
            lxc.customize "net", ""

            # Management interface
            lxc.customize "net.0.type",         "veth"
            lxc.customize "net.0.flags",        "up"
            lxc.customize "net.0.link",         "br-mgt0"
            lxc.customize "net.0.name",         "mgt0"
            lxc.customize "net.0.veth.pair",    "proxygwb-mgt0"
            lxc.customize "net.0.ipv4.address", "10.0.0.15/24"
            lxc.customize "net.0.ipv4.gateway", "10.0.0.1"

            # WAN interface - wild
            lxc.customize "net.1.type",         "veth"
            lxc.customize "net.1.flags",        "up"
            lxc.customize "net.1.link",         "br-wan2"
            lxc.customize "net.1.name",         "wan0"
            lxc.customize "net.1.veth.pair",    "proxygwb-wan0"

            # WAN interface - safe
            lxc.customize "net.2.type",         "veth"
            lxc.customize "net.2.flags",        "up"
            lxc.customize "net.2.link",         "br-wan2-gwb"
            lxc.customize "net.2.name",         "wan0p"
            lxc.customize "net.2.veth.pair",    "proxygwb-wan0p"
        end
    end
end
